(define (or-gate a1 a2 output)
	(let ((invert-1 (make-wire))
		  (invert-2 (make-wire))
		  (and-output (make-wire)))
		(inverter a1 invert-1)
		(inverter a2 invert-2)
		(and-gate invert-1 invert-2 and-output)
		(inverter and-output output))
	'ok)